FROM python:3.13-slim AS build

RUN apt-get update && \
   apt-get install -y libpq-dev gcc

RUN python -m venv /opt/venv

ENV PATH="/opt/venv/bin:$PATH"

COPY requirements.txt .
RUN pip install -r requirements.txt


FROM python:3.13-slim

RUN apt-get update && \
apt-get install --no-install-recommends -y libpq-dev && \
rm -rf /var/lib/apt/lists/*

COPY --from=build /opt/venv /opt/venv

ENV PATH="/opt/venv/bin:$PATH"


WORKDIR /app

COPY app.py ./